// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzmbrxzltqjqacwvkrbd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6bWJyeHpsdHFqcWFjd3ZrcmJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NjAwMzIsImV4cCI6MjA2OTEzNjAzMn0.Hj9j_oLLyUqyfIr7XWFz1CLWerU7LnqNntTNCTeajac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});